version: '3.13'

services:
  document_quality_api:
    build: .
    container_name: document-quality-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    restart: always
