version: '3.13'

services:
  document-quality-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: document_quality_api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always
