services:
  doc_api:
    image: fastapi-gpu:latest
    build:
      context: ..  # Points to Document-Quality-API/
      dockerfile: docker/Dockerfile
      args:
        PIP_EXTRA_INDEX_URL: "https://pypi.org/simple"
        PIP_RETRIES: "5"
    ports:
      - "8000:8000"
    deploy:
      restart_policy:
        condition: unless-stopped
    volumes:
      - C:/Users/erraheln/Desktop/iqa/storage:/app/storage
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility